---
title: "PSTAT 131 Final Project Report"
subtitle: "AirBNB Price Prediction"
author: "Brian Che"
date: "2022-11-19"
output:
  html_document:
    code_folding: show
    toc: true
    toc_float: true
    theme: united
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Introduction

Los Angeles listings.csv <http://insideairbnb.com/get-the-data/>

```{r,warning=FALSE,message=FALSE, class.source = 'fold-hide'}
# load libraries
library(tidyverse)
library(tidymodels)
```

```{r}
# read in data
data <- read_csv("data/listings.csv") 
glimpse(data)

NAnalysis <- data %>% 
  group_by(neighbourhood_group) %>% summarise(Mean_Price = mean(price))

ggplot(NAnalysis, aes(x = reorder(neighbourhood_group, -Mean_Price), y = Mean_Price)) + 
  geom_bar(stat="identity",colour="black", fill = "tomato3") + 
  labs(title="Average Price of Rooms in each Neighbourhood Group") + 
  theme(plot.title = element_text(hjust = 0.5),
        plot.subtitle = element_text(hjust = 0.5), legend.position = c(0.8, 0.5)) + xlab("") + ylab("Mean Price")
```

## Exploratory Data Analysis

<https://www.kaggle.com/code/upadorprofzs/understand-your-data-airbnb-reservations>

## Data Splitting & Cross-validation

Text

## Model Fitting

Text

## Model Selection & Performance

Text

## Conclusion

Text

=======

## References

### Tabset Reference {.tabset}

#### Test 1

Text 1

#### Test 2

Text 2

#### Test 3

Text 3

### Chunk code-fold show / code-fold hide

```{r,warning=FALSE,message=FALSE, class.source = 'fold-hide'}
# load libraries
library(tidyverse)
library(tidymodels)
```

```{r,warning=FALSE,message=FALSE, class.source = 'fold-show'}
# load libraries
library(tidyverse)
library(tidymodels)
```
